# permissions for end users to view masters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: master-viewer-role
rules:
- apiGroups:
  - crd.cxwen.com
  resources:
  - masters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - crd.cxwen.com
  resources:
  - masters/status
  verbs:
  - get
