# permissions for end users to edit matrices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: matrix-editor-role
rules:
- apiGroups:
  - crd.cxwen.com
  resources:
  - matrices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.cxwen.com
  resources:
  - matrices/status
  verbs:
  - get
