# permissions for end users to edit networkplugins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: networkplugin-editor-role
rules:
- apiGroups:
  - crd.cxwen.com
  resources:
  - networkplugins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.cxwen.com
  resources:
  - networkplugins/status
  verbs:
  - get
