# permissions for end users to view networkplugins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: networkplugin-viewer-role
rules:
- apiGroups:
  - crd.cxwen.com
  resources:
  - networkplugins
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - crd.cxwen.com
  resources:
  - networkplugins/status
  verbs:
  - get
