
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - crd.cxwen.com
  resources:
  - dns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.cxwen.com
  resources:
  - dns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - crd.cxwen.com
  resources:
  - etcdclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.cxwen.com
  resources:
  - etcdclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - crd.cxwen.com
  resources:
  - masters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.cxwen.com
  resources:
  - masters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - crd.cxwen.com
  resources:
  - matrices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.cxwen.com
  resources:
  - matrices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - crd.cxwen.com
  resources:
  - networkplugins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - crd.cxwen.com
  resources:
  - networkplugins/status
  verbs:
  - get
  - patch
  - update
