name: publish to docker hub

on:
  push:
    branches: [ master ]
    tags: 
      - 'v*.*.*'
  pull_request:
    branches: [ master ]
    tags: 
      - 'v*.*.*'
  release:
    types: [published]

jobs:
  build:
    runs-on: xwcheng/kubebuilder:2.3.1
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: xwcheng/matrix
        username: ${{ secrets.dockerhub_password }}
        password: ${{ secrets.dockerhub_username }}
        tag_names: true
        cache: true
